### ISSUE TITLE
CustomGeometry

### ISSUE THREAD

**Issue by NitinManepalli7** [hofk/threejsResources#1]
Hello, I am trying to convert your script to type script i wasn't able to understand what is CustomGeometry is doing as It is leading me to void errors. can you please  help me I am trying to built a human skeleton structure and animate it with the json file. I would really appreciate if you could help and give some insights regarding my project. i don't know wheather it is right place to post my question. if it is not I am sorry. 
Thank you

**Comment by hofk** [comment]
> i don't know wheather it is right place to post my question.

This fits better to  https://discourse.threejs.org/
I am also active there under hofk and can answer the question. You can address me directly with @hofk. Other participants can also contribute, I do not use  _type script_.

https://discourse.threejs.org/t/pino-a-procedurally-generated-and-moved-skeleton-figure/36184
